const icons={grid:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="7" height="7" rx="2"/><rect x="13" y="4" width="7" height="7" rx="2"/><rect x="4" y="13" width="7" height="7" rx="2"/><rect x="13" y="13" width="7" height="7" rx="2"/></svg>',calendar:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3v4M16 3v4M4 10h16"/></svg>',cards:'<svg viewBox="0 0 24 24"><rect x="5" y="4" width="14" height="16" rx="3"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>',library:'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/><path d="M7 4v16"/></svg>',spark:'<svg viewBox="0 0 24 24"><path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3z"/><path d="M19 15l.8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15z"/></svg>',settings:'<svg viewBox="0 0 24 24"><path d="M12 15.5A3.5 3.5 0 1 0 12 8a3.5 3.5 0 0 0 0 7.5z"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.3a2 2 0 1 1-4 0V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1A2 2 0 1 1 4.2 17l.1-.1A1.7 1.7 0 0 0 4.6 15 1.7 1.7 0 0 0 3 14H2.7a2 2 0 1 1 0-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7A2 2 0 1 1 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10 3V2.7a2 2 0 1 1 4 0V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1A2 2 0 1 1 19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9c.2.6.8 1 1.6 1h.3a2 2 0 1 1 0 4H21c-.8 0-1.4.4-1.6 1z"/></svg>',shield:'<svg viewBox="0 0 24 24"><path d="M12 3l7 3v5c0 5-3 8-7 10-4-2-7-5-7-10V6l7-3z"/><path d="M9 12l2 2 4-5"/></svg>',bell:'<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="M20 6L9 17l-5-5"/></svg>',send:'<svg viewBox="0 0 24 24"><path d="M22 2L11 13"/><path d="M22 2l-7 20-4-9-9-4 20-7z"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5"/></svg>',image:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="14" rx="3"/><path d="M8 14l2.5-3 3 4 2-2.4L20 18"/><circle cx="9" cy="9" r="1"/></svg>'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||'');
const items=[
{title:'Street Interview Hook',status:'ready',date:'Aug 28',day:28,platforms:['Instagram','TikTok'],template:'Default Hook Title v1',compliance:'Pass',hook:'Why does this feel like a real street interview?',caption:'Realism comes from camera distance, natural pauses, and imperfect street audio. #ai #video #creator #socialmedia #filmmaking',variants:['Why does this feel real?','Why does this feel like a real street interview?'],img:'assets/thumbs/street_interview_hook_aug25.jpg'},
{title:'Lip Makeup Hook',status:'approved',date:'Aug 29',day:29,platforms:['Instagram','TikTok'],template:'Default Hook Title v1',compliance:'Pass',hook:'The face detail makes or breaks beauty AI.',caption:'For beauty clips, texture, lighting, and small hand movements matter more than a flashy prompt. #beauty #ai #video #makeup #creator',variants:['Beauty AI Needs Detail','The face detail makes or breaks beauty AI.'],img:'assets/thumbs/lip_makeup_hook_aug25.jpg'},
{title:'AI Video Builder',status:'scheduled',date:'Sep 01',day:1,platforms:['Instagram'],template:'Default Hook Title v1',compliance:'Needs check',hook:'Build the shot before generating.',caption:'Write the camera, subject, action, and lighting first. Then generate. #ai #videotools #workflow #content #automation',variants:['Build The Shot First','Build the shot before generating.'],img:'assets/thumbs/artpro_ai_video_builder_aug23.jpg'},
{title:'Dragon Product Ad',status:'posted',date:'Aug 22',day:22,platforms:['Instagram','Pinterest'],template:'Default Hook Title v1',compliance:'Pass',hook:'A product ad needs one impossible image.',caption:'Surreal ads work best when the product still stays readable. #advertising #aiart #productvideo #design #creative',variants:['Impossible Product Ad','A product ad needs one impossible image.'],img:'assets/thumbs/perfume_dragon_ad.jpg'},
{title:'GTA Free Roam Test',status:'ready',date:'Aug 30',day:30,platforms:['Instagram','TikTok'],template:'Bahnschrift gameplay overlay',compliance:'Pass',hook:'This is the framing that feels like gameplay.',caption:'Third-person framing makes AI game footage feel more believable than cinematic angles. #gaming #ai #gta #video #creator',variants:['Gameplay Framing','This is the framing that feels like gameplay.'],img:'assets/thumbs/gta_seedance_top_overlay.jpg'},
{title:'Caesar Rubicon Trap',status:'edited',date:'Not set',day:null,platforms:['X','Reddit'],template:'Default Hook Title v1',compliance:'Needs check',hook:'History is easier to remember as a trap.',caption:'Draft caption waiting for approval.',variants:['History As A Trap','History is easier to remember as a trap.'],img:'assets/thumbs/caesar_rubicon_trap.jpg'},
{title:'Noki Prompt Below Title',status:'approved',date:'Sep 04',day:4,platforms:['Instagram'],template:'Prompt below title',compliance:'Failed',hook:'The prompt should not fight the image.',caption:'When the overlay is too busy, the viewer stops watching the video. #design #ai #videoediting #socialmedia #creator',variants:['Prompt Below Title','The prompt should not fight the image.'],img:'assets/thumbs/noki_prompt_below_title.jpg'},
{title:'Dragon Vertical Edit',status:'posted',date:'Aug 24',day:24,platforms:['TikTok','Pinterest'],template:'Default Hook Title v1',compliance:'Pass',hook:'Vertical crops decide the whole ad.',caption:'A good vertical crop keeps the subject, motion, and title readable at the same time. #tiktok #pinterest #video #design #ads',variants:['Vertical Crop Test','Vertical crops decide the whole ad.'],img:'assets/thumbs/dragons_rotated_vertical.jpg'}
];
let activeStatus='all', zoom=1, showImages=true; const zoomNames=['Compact','Comfort','Focus'];
function cls(v){return v==='Pass'?'':v==='Needs check'?'warn':'bad'}
function platformHtml(a){return a.map(p=>`<span class="platform">${p}</span>`).join('')}
function renderCards(filter='all',q=''){const root=document.getElementById('contentCards');root.innerHTML='';q=q.toLowerCase();items.filter(i=>(filter==='all'||i.status===filter)&&JSON.stringify(i).toLowerCase().includes(q)).forEach((it,idx)=>root.insertAdjacentHTML('beforeend',`<article class="content-card" data-index="${idx}"><div class="preview"><img src="${it.img}" alt="${it.title} preview"><span class="badge ${it.status}">${it.status}</span></div><div class="card-body"><div class="card-top"><h3>${it.title}</h3><span class="date-text">${it.date}</span></div><div class="platforms">${platformHtml(it.platforms)}</div><div class="meta"><span><strong>Hook:</strong> ${it.hook}</span><span><strong>Template:</strong> ${it.template}</span><span><strong>Caption:</strong> ${it.caption.slice(0,82)}...</span></div><div class="card-actions"><span class="compliance ${cls(it.compliance)}">Template: ${it.compliance}</span><button class="open-detail">Details</button></div></div></article>`))}
function renderCalendar(){const root=document.getElementById('calendarGrid');root.className=`calendar-grid zoom-${['compact','comfort','focus'][zoom]} ${showImages?'show-images':''}`;root.innerHTML='';['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach(d=>root.insertAdjacentHTML('beforeend',`<div class="day-name">${d}</div>`));for(let i=0;i<35;i++){const d=i<5?27+i:i-4;const muted=i<5||d>31?'muted':'';const dayItems=items.filter(x=>x.day===d);root.insertAdjacentHTML('beforeend',`<div class="day ${muted}"><div class="day-number">${d}</div>${dayItems.map(it=>`<div class="cal-event" data-title="${it.title}"><img src="${it.img}" alt="${it.title}"><div class="cal-title"><span class="dot ${it.status}"></span>${it.title}</div></div>`).join('')}</div>`)}document.getElementById('zoomLabel').textContent=zoomNames[zoom];document.getElementById('previewToggle').classList.toggle('active',showImages)}
function renderQueue(){document.getElementById('queueList').innerHTML=items.filter(i=>['ready','approved','scheduled'].includes(i.status)).slice(0,3).map(i=>`<li><img src="${i.img}" alt="${i.title}"><div><strong>${i.title}</strong><small>${i.platforms.join(' + ')} · ${i.status} · ${i.date}</small></div></li>`).join('')}
renderCards();renderCalendar();renderQueue();
document.querySelectorAll('.chip').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeStatus=btn.dataset.status;renderCards(activeStatus,searchInput.value)}));searchInput.addEventListener('input',()=>renderCards(activeStatus,searchInput.value));
previewToggle.addEventListener('click',()=>{showImages=!showImages;renderCalendar()});zoomOut.addEventListener('click',()=>{zoom=Math.max(0,zoom-1);renderCalendar()});zoomIn.addEventListener('click',()=>{zoom=Math.min(2,zoom+1);renderCalendar()});
const drawer=document.getElementById('drawer');contentCards.addEventListener('click',e=>{const card=e.target.closest('.content-card');if(!card||!e.target.closest('.open-detail'))return;const it=items[+card.dataset.index];drawerContent.innerHTML=`<p class="eyebrow">${it.status} / ${it.date}</p><h2>${it.title}</h2><img class="detail-img" src="${it.img}" alt="${it.title}"><div class="platforms">${platformHtml(it.platforms)}</div><div class="detail-section"><h4>Hook/title</h4><p>${it.hook}</p></div><div class="detail-section"><h4>Caption</h4><p>${it.caption}</p></div><div class="detail-section"><h4>Template + compliance</h4><p>${it.template} — ${it.compliance}</p></div><div class="detail-section"><h4>Title variant history</h4><p>${it.variants.join(' → ')}</p></div>`;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false')});drawerClose.addEventListener('click',()=>{drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')});drawer.addEventListener('click',e=>{if(e.target===drawer)drawerClose.click()});
